# baseURL
@baseURL = http://localhost:5000

###
# User Signup
POST {{ baseURL }}/auth/signup
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "123456789",
    "fullName": "Nguyen Van A"
}

###
# Admin Login
POST {{ baseURL }}/auth/login
Content-Type: application/json

{
    "email": "admin@thsp.edu.vn",
    "password": "admin@123"
}

###
# User Login
POST {{ baseURL }}/auth/login
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "123456789"
}

###
# Refresh Token
POST {{ baseURL }}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "PASTE_REFRESH_TOKEN_HERE"
}

###
# Get Profile (requires Authorization header)
GET {{ baseURL }}/auth/profile
Content-Type: application/json
Authorization: Bearer PASTE_ACCESS_TOKEN_HERE

###
# User Logout (requires Authorization header)
POST {{ baseURL }}/auth/logout
Content-Type: application/json
Authorization: Bearer PASTE_ACCESS_TOKEN_HERE
